import React, { Fragment } from 'react';
import { Helmet } from 'react-helmet';
import { node } from 'prop-types';
import { Box } from '@chakra-ui/react';

import Favicon from './assets/logo.png';

import './assets/styles.css';

const SEO_TITLE = 'Perf Workshop - For Demo Only';
const SEO_DESCRIPTION = 'This site generated by using Gatsby.js';

function MainLayout({ children }) {
  return (
    <Fragment>
      <Helmet>
        <title>{SEO_TITLE}</title>
        <link rel="icon" type="image/png" href={Favicon} />
        <meta property="og:title" content={SEO_TITLE} />
        <meta property="og:site_name" content={SEO_TITLE} />
        <meta property="og:description" content={SEO_DESCRIPTION} />
        <meta name="twitter:title" content={SEO_TITLE} />
        <meta name="twitter:description" content={SEO_DESCRIPTION} />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:creator" content="@idindrakusuma" />{' '}
      </Helmet>
      <Box id="page" maxWidth="100%" bgColor="white">
        <Box boxShadow="2xl" maxWidth="500px" display="block" margin="auto">
          {children}
        </Box>
      </Box>
    </Fragment>
  );
}

MainLayout.propTypes = {
  children: node.isRequired,
};

export default MainLayout;
