import React, { Fragment } from 'react';
import { Helmet } from 'react-helmet';
import { node } from 'prop-types';
import { Box } from '@chakra-ui/react';

import Favicon from './assets/logo.png';

import './assets/styles.css';

const SEO_TITLE = 'Perf Workshop - For Demo Only';
const SEO_DESCRIPTION = 'This site generated by using Gatsby.js';

function MainLayout({ children }) {
  return (
    <Fragment>
      <Helmet>
        <title>{SEO_TITLE}</title>
        <link rel="icon" type="image/png" href={Favicon} />
        <meta property="og:title" content={SEO_TITLE} />
        <meta property="og:site_name" content={SEO_TITLE} />
        <meta property="og:description" content={SEO_DESCRIPTION} />
        <meta name="twitter:title" content={SEO_TITLE} />
        <meta name="twitter:description" content={SEO_DESCRIPTION} />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:creator" content="@idindrakusuma" />

        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600&family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;1,200;1,300;1,400;1,600&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
      </Helmet>
      <Box id="page" maxWidth="100%" minHeight="100vh" bgColor="white">
        <Box boxShadow="2xl" maxWidth="500px" display="block" margin="auto">
          {children}
        </Box>
      </Box>
    </Fragment>
  );
}

MainLayout.propTypes = {
  children: node.isRequired,
};

export default MainLayout;
